--- iozone/src/current/makefile.orig	2013-07-09 00:12:12.000000000 +0200
+++ iozone/src/current/makefile	2013-12-07 00:22:26.159512000 +0100
@@ -9,12 +9,12 @@
 #		convex, FreeBSD, OpenBSD, OSFV3, OSFV4, OSFV5, SCO
 #		SCO_Unixware_gcc,NetBSD,TRU64, Mac OS X
 
-CC	= cc
-C89	= c89
+#CC	= cc
+#C89	= c89
 GCC	= gcc
 CCS	= /usr/ccs/bin/cc
 NACC	= /opt/ansic/bin/cc
-CFLAGS	=
+#CFLAGS	=
 S10GCCFLAGS    = -m64
 S10CCFLAGS     = -m64
 FLAG64BIT      = -m64
