#!/bin/sh

if [ `uname -m` = x86_64 ]; then
echo "Setting up ipkg arch-file"
mkdir -p /opt/etc/ipkg
cat >> /opt/etc/ipkg/arch.conf << EOF
arch all 1
arch any 6
arch noarch 11
arch x86_64 16
EOF
fi

touch /etc/profile
if ! grep '^PATH=.*/opt/bin' /etc/profile >/dev/null 2>&1 ; then
  echo
  # echo "PATH=/opt/bin:/opt/sbin:\$PATH" >> /etc/profile
fi


if ! grep '^# Optware setup' /usr/local/etc/init.d/rc.local >/dev/null 2>&1
then
  # echo "Modifying /usr/local/etc/init.d/rc.local"
  # [ ! -e /usr/local/etc/init.d/rc.local ] && echo "#!/bin/sh" >/usr/local/etc/init.d/rc.local
  # sed -i -e '/^exit 0/d' /usr/local/etc/init.d/rc.local
  # cat >>/usr/local/etc/init.d/rc.local <<EOF

# Optware setup
[ -x /usr/local/etc/init.d/rc.optware ] && /usr/local/etc/init.d/rc.optware start

exit 0
EOF
  # chmod 755 /usr/local/etc/init.d/rc.local
fi
